name: Ping site and update data
on:
  schedule:
    - cron: "0 0 * * *" # Every 24 hours

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Ping site
        run: python scripts/ping_site.py
        env:
          PING_URL: ${{ secrets.PING_URL }}
      - name: Commit data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data
          git commit -m "Update ping data" || echo "No changes to commit"
      - name: Push changes
        run: git push
